version: "{build}"
image: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
  - JAVA_HOME: C:/Program Files/Java/jdk1.8.0

build_script:
- java -version
- mvnw.cmd -Dsurefire.rerunFailingTestsCount=1 -B clean install

on_failure:
- cat **/**/target/surefire-reports/*.txt | grep -A 5 -B 5 'ERROR'

cache:
- C:/Users/appveyor/.m2
