version: "{build}"
image: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
    - JAVA_HOME: C:/Program Files/Java/jdk1.8.0

build_script:
  - java -version
  - mvnw.cmd -Dsurefire.rerunFailingTestsCount=1 -B clean install

on_failure:
  - ps: |
      7z a -r surefire-reports.zip '**\target\surefire-reports\*'
      Push-AppveyorArtifact surefire-reports.zip -DeploymentName 'Surefire Reports'

cache:
  - C:/Users/appveyor/.m2
