language: java
sudo: true
dist: trusty

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode9.3

script:
- java -version
- ./mvnw -B clean install -DCASSANDRA.CI.BUILD=true

after_failure:
- cat **/**/target/surefire-reports/*.txt


cache:
  directories:
  - $HOME/.m2
